<a href="https://colab.research.google.com/github/feiduobaby/good-first-issue/blob/main/Homework6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-10-31 05:37:39--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.05s   

2025-10-31 05:37:40 (17.5 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [2]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
!head car_fuel_efficiency.csv

engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
170,3,159,3413.433758606219,17.7,2003,Europe,Gasoline,All-wheel drive,0,13.231728906241411
130,5,97,3149.6649342200353,17.8,2007,USA,Gasoline,Front-wheel drive,0,13.688217435463793
170,,78,3079.03899736884,15.1,2018,Europe,Gasoline,Front-wheel drive,0,14.246340998160866
220,4,,2542.392401828378,20.2,2009,USA,Diesel,All-wheel drive,2,16.91273559598635
210,1,140,3460.870989989018,14.4,2009,Europe,Gasoline,All-wheel drive,2,12.488369121964562
190,3,,2484.883986036068,14.7,2008,Europe,Gasoline,All-wheel drive,-1,17.271818372724237
240,7,127,3006.5422872171457,22.2,2012,USA,Gasoline,Front-wheel drive,1,13.210412112385608
150,4,239,3638.6577802809,17.3,2020,USA,Diesel,All-wheel drive,1,12.848883861524026
250,1,174,2714.219309645285,10.3,2016,Asia,Diesel,Front-wheel drive,-1,16.823553726916543


In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [5]:
df.columns = df.columns.str.lower()

In [6]:
df.value_counts()

engine_displacement  num_cylinders  horsepower  vehicle_weight  acceleration  model_year  origin  fuel_type  drivetrain         num_doors  fuel_efficiency_mpg
380                  6.0            134.0       1904.966269     16.4          2022        Europe  Gasoline   All-wheel drive     1.0       20.259049              1
30                   3.0            139.0       3169.620573     12.2          2020        Europe  Gasoline   Front-wheel drive   2.0       14.020636              1
                     4.0            146.0       2142.496383     18.7          2015        Asia    Diesel     Front-wheel drive   0.0       18.882554              1
                     6.0            155.0       2935.186300     20.1          2008        Asia    Diesel     Front-wheel drive   1.0       15.262094              1
40                   4.0            103.0       2103.882204     14.5          2003        USA     Diesel     Front-wheel drive   0.0       19.130571              1
                                                                                                                                                                 ..
50                   2.0            160.0       3541.503022     13.0          2017        USA     Gasoline   Front-wheel drive  -1.0       12.289811              1
                                    92.0        2097.599332     13.4          2018        Europe  Gasoline   Front-wheel drive   0.0       19.914258              1
40                   6.0            194.0       3703.070061     12.6          2004        Europe  Gasoline   Front-wheel drive   1.0       12.594446              1
                     5.0            196.0       2310.681425     16.7          2003        Asia    Gasoline   Front-wheel drive   1.0       18.485111              1
                                    157.0       2942.639275     11.2          2007        Europe  Diesel     Front-wheel drive  -1.0       15.742445              1
Name: count, Length: 7333, dtype: int64

In [7]:
df.columns[df.isnull().any()]

Index(['num_cylinders', 'horsepower', 'acceleration', 'num_doors'], dtype='object')

In [8]:
df.num_cylinders = pd.to_numeric(df.num_cylinders, errors='coerce').fillna(0)
df.horsepower = pd.to_numeric(df.horsepower, errors='coerce').fillna(0)
df.acceleration = pd.to_numeric(df.acceleration, errors='coerce').fillna(0)
df.num_doors = pd.to_numeric(df.num_doors, errors='coerce').fillna(0.0)

In [31]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [54]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
y_train = df_train.astype('str').values
y_val = df_val.astype('str').values
y_test = df_test.astype('str').values

In [55]:
categorical = ['origin', 'fuel_type', 'drivetrain']
numerical = ['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight', 'acceleration', 'model_year', 'num_doors']

In [56]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

1 decision trees

In [57]:
df['origin'].unique()

array([nan], dtype=object)

In [58]:
origin_values = {
    1:'Europe',
    2:'USA',
    0:'Asia'
}
df.origin = df.origin.map(origin_values)

In [59]:
df['fuel_type'].unique()

array([nan], dtype=object)

In [60]:
fuel_type_values = {
    1:'Gasoline',
    0:'Diesel'
}
df.fuel_type = df.fuel_type.map(fuel_type_values)

In [61]:
df['drivetrain'].unique()

array([nan], dtype=object)

In [62]:
drivetrain_values = {
    1:'All-wheel drive',
    0:'Front-wheel drive'
}
df.drivetrain = df.drivetrain.map(drivetrain_values)

In [63]:
def assess_risk(car):
    if car['drivetrain'] == 'All-wheel drive':
        if car['fuel_type'] == 'Gasoline':
            return 'default'
        else:
            if car['origin'] == 'USA':
                return 'ok'
            else:
                return 'default'
xi = df_train.iloc[0].to_dict()
assess_risk(xi)

In [64]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text
dv = DictVectorizer(sparse=False)
train_dicts = df_train.fillna(0).to_dict(orient = 'records')
X_train = dv.fit_transform(train_dicts)
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [71]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)
probs = dt.predict_proba(X_val)

print(type(probs), getattr(probs, "shape", None))
#roc_auc_score(y_val, y_pred)

<class 'list'> None
